#!/bin/bash
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $SCRIPT_DIR/..

echo "Bumping version: $1"

rm -rf versioned_docs/version-*
rm -f versioned_sidebars/version-*-sidebars.json

printf '["%s"]' "$1" > versions.json
cp -r docs "versioned_docs/version-$1"
echo '{"docsSidebar": [{"type": "autogenerated", "dirName": "."}]}' > "versioned_sidebars/version-$1-sidebars.json"
